Add item requests
Michail-A/java-shareit pull request #5
Opened 2023-12-17 14:08 UTC by Michail-A

2023-12-17 20:54 UTC, NikolaiDem requested changes

2023-12-17 20:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/RequestServiceImpl.java
> +        List<Item> items = itemRepository.findAll();
Нужно найти items, по списку requests, все читать не нужно

2023-12-17 20:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/RequestServiceImpl.java
> +                        .addAll(items.stream()
Чтобы не перебирать stream каждый раз, лучше items представить в виде мамы, где ключ - request, а значение - список item-ов

2023-12-17 20:54 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    void findByBookerIdOrderByIdDesc() {
Пустые методы для чего ?
Аналогично для остальных репозиториев без кастомных методов

2023-12-17 22:00 UTC, Michail-A commented on src/main/java/ru/practicum/shareit/request/RequestServiceImpl.java
> +                        .addAll(items.stream()
Немного не понял, как сделать. Чтобы заполнить Map все равно же придется перебирать значения?

2023-12-18 04:14 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/RequestServiceImpl.java
> +                        .addAll(items.stream()
items.stream()
. collect(groupingBy(item -> item.getRequest().getId()))

Получена мапа, из которой по запросу сразу можно найти все предметы

2023-12-18 04:14 UTC, NikolaiDem approved these changes

2023-12-18 21:32 UTC, merged